//
//  CreateTravelUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/25.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("여행 생성 UseCase 테스트", .tags(.useCase, .travel))
struct CreateTravelUseCaseTests {

    // MARK: - Test Fixtures

    private func makeValidInput() -> CreateTravelInput {
        CreateTravelInput(
            title: "제주도 여행",
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400 * 3), // 3일 후
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0,
            destinationCurrency: "KRW",
            currencies: ["KRW"]
        )
    }

    // MARK: - Happy Path Tests

    @Test("TC-TRAVEL-001: 정상적인 여행 생성")
    func createTravel_withValidInput_shouldReturnTravel() async throws {
        // given
        let input = makeValidInput()
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.title == "제주도 여행")
        #expect(result.countryCode == "KR")
        #expect(result.baseCurrency == "KRW")
        #expect(!result.id.isEmpty)
    }

    @Test("TC-TRAVEL-002: 여행 생성 시 초대 코드 발급")
    func createTravel_shouldGenerateInviteCode() async throws {
        // given
        let input = makeValidInput()
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        let inviteCode = try #require(result.inviteCode)
        #expect(!inviteCode.isEmpty)
        #expect(inviteCode.hasPrefix("INV"))
    }

    @Test("TC-TRAVEL-003: 여행 생성 시 상태는 active")
    func createTravel_shouldHaveActiveStatus() async throws {
        // given
        let input = makeValidInput()
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.status == .active)
    }

    @Test("TC-TRAVEL-004: 여행 생성 시 생성자는 owner 역할")
    func createTravel_shouldSetCreatorAsOwner() async throws {
        // given
        let input = makeValidInput()
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.role == "owner")
    }

    // MARK: - Edge Case Tests

    @Test("TC-TRAVEL-005: 다양한 국가 코드로 여행 생성", arguments: [
        ("JP", "일본", "JPY"),
        ("US", "미국", "USD"),
        ("TH", "태국", "THB"),
        ("VN", "베트남", "VND")
    ])
    func createTravel_withVariousCountries_shouldSucceed(
        countryCode: String,
        koreanName: String,
        currency: String
    ) async throws {
        // given
        let input = CreateTravelInput(
            title: "\(koreanName) 여행",
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400 * 5),
            countryCode: countryCode,
            koreanCountryName: koreanName,
            baseCurrency: "KRW",
            baseExchangeRate: 1.0,
            destinationCurrency: currency,
            currencies: ["KRW", currency]
        )
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.countryCode == countryCode)
        #expect(result.koreanCountryName == koreanName)
        #expect(result.destinationCurrency == currency)
    }

    @Test("TC-TRAVEL-006: 당일 여행 생성 (시작일 == 종료일)")
    func createTravel_withSameDayTrip_shouldSucceed() async throws {
        // given
        let today = Date()
        let input = CreateTravelInput(
            title: "당일치기 여행",
            startDate: today,
            endDate: today,
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0
        )
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.title == "당일치기 여행")
    }

    @Test("TC-TRAVEL-007: 긴 제목으로 여행 생성")
    func createTravel_withLongTitle_shouldSucceed() async throws {
        // given
        let longTitle = String(repeating: "여행", count: 50) // 100자
        let input = CreateTravelInput(
            title: longTitle,
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400),
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0
        )
        let useCase = CreateTravelUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.title == longTitle)
    }

    // MARK: - Validation Tests (Known Issues - 원본 코드에 유효성 검증 없음)

    @Test("TC-TRAVEL-008: 빈 제목으로 여행 생성 시도",
          .disabled("Known Issue: CreateTravelInput에 제목 유효성 검증 없음"))
    func createTravel_withEmptyTitle_shouldThrowError() async {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 비즈니스 규칙 (기대 동작)                            │
        ├─────────────────────────────────────────────────────┤
        │ - 여행 제목은 필수 입력 항목                         │
        │ - 빈 문자열 또는 공백만 있는 경우 에러               │
        ├─────────────────────────────────────────────────────┤
        │ 현재 상태                                           │
        │ - CreateTravelInput에 유효성 검증 로직 없음          │
        │ - 빈 제목도 그대로 저장됨                            │
        ├─────────────────────────────────────────────────────┤
        │ 리팩토링 제안                                       │
        │ - CreateTravelInput.init에서 guard 검증 추가        │
        │ - TravelValidationError.emptyTitle 정의             │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let input = CreateTravelInput(
            title: "",
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400),
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0
        )
        let useCase = CreateTravelUseCase()

        // then: 기대 - TravelValidationError.emptyTitle throw
        // 현재는 유효성 검증 없이 생성됨
    }

    @Test("TC-TRAVEL-009: 종료일이 시작일보다 이전인 경우",
          .disabled("Known Issue: 날짜 유효성 검증 없음"))
    func createTravel_withEndDateBeforeStartDate_shouldThrowError() async {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 비즈니스 규칙 (기대 동작)                            │
        ├─────────────────────────────────────────────────────┤
        │ - 종료일은 시작일과 같거나 이후여야 함               │
        │ - 종료일 < 시작일인 경우 에러                        │
        ├─────────────────────────────────────────────────────┤
        │ 현재 상태                                           │
        │ - 날짜 순서 검증 로직 없음                           │
        │ - 잘못된 날짜 범위도 저장됨                          │
        ├─────────────────────────────────────────────────────┤
        │ 리팩토링 제안                                       │
        │ - CreateTravelInput.init에서 날짜 검증 추가         │
        │ - TravelValidationError.invalidDateRange 정의       │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let startDate = Date()
        let endDate = startDate.addingTimeInterval(-86400) // 하루 전
        let input = CreateTravelInput(
            title: "잘못된 여행",
            startDate: startDate,
            endDate: endDate,
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0
        )
        let useCase = CreateTravelUseCase()

        // then: 기대 - TravelValidationError.invalidDateRange throw
        // 현재는 유효성 검증 없이 생성됨
    }
}
