//
//  DeleteTravelUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/25.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("여행 삭제 UseCase 테스트", .tags(.useCase, .travel))
struct DeleteTravelUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-TRAVEL-024: 정상적인 여행 삭제")
    func deleteTravel_withValidId_shouldSucceed() async throws {
        // given
        let travelId = "MOCK-1"
        let useCase = DeleteTravelUseCase()

        // when & then: 에러 없이 완료
        try await useCase.execute(id: travelId)
    }

    @Test("TC-TRAVEL-025: 삭제 후 목록에서 제외 확인")
    func deleteTravel_shouldRemoveFromList() async throws {
        // given
        let createUseCase = CreateTravelUseCase()
        let deleteUseCase = DeleteTravelUseCase()
        let fetchUseCase = FetchTravelsUseCase()

        // 여행 생성
        let input = CreateTravelInput(
            title: "삭제 테스트 여행",
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400),
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0
        )
        let created = try await createUseCase.execute(input: input)
        let createdId = created.id

        // when: 삭제
        try await deleteUseCase.execute(id: createdId)

        // then: 목록에서 확인
        let fetchInput = FetchTravelsInput(limit: 100, page: 1, status: .active)
        let travels = try await fetchUseCase.execute(input: fetchInput)
        let found = travels.contains { $0.id == createdId }
        #expect(!found)
    }

    // MARK: - Edge Case Tests

    @Test("TC-TRAVEL-026: 이미 삭제된 여행 재삭제 시도")
    func deleteTravel_alreadyDeleted_shouldHandleGracefully() async throws {
        // given
        let createUseCase = CreateTravelUseCase()
        let deleteUseCase = DeleteTravelUseCase()

        let input = CreateTravelInput(
            title: "재삭제 테스트",
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400),
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0
        )
        let created = try await createUseCase.execute(input: input)
        let travelId = created.id

        // when: 첫 번째 삭제
        try await deleteUseCase.execute(id: travelId)

        // then: 두 번째 삭제도 에러 없이 처리 (idempotent)
        // MockRepository는 없는 ID 삭제 시에도 에러를 던지지 않음
        try await deleteUseCase.execute(id: travelId)
    }

    @Test("TC-TRAVEL-027: 빈 ID로 삭제 시도",
          .disabled("Known Issue: ID 유효성 검증 없음"))
    func deleteTravel_withEmptyId_shouldThrowError() async {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 비즈니스 규칙 (기대 동작)                            │
        ├─────────────────────────────────────────────────────┤
        │ - ID는 필수 파라미터                                 │
        │ - 빈 문자열 ID는 에러                                │
        ├─────────────────────────────────────────────────────┤
        │ 현재 상태                                           │
        │ - ID 유효성 검증 없음                                │
        │ - 빈 ID도 Repository로 전달됨                        │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let emptyId = ""
        let useCase = DeleteTravelUseCase()

        // then: 기대 - TravelValidationError.invalidId throw
    }

    // MARK: - Authorization Tests (Known Issues)

    @Test("TC-TRAVEL-028: 다른 사용자의 여행 삭제 시도",
          .disabled("Known Issue: 권한 검증 로직이 UseCase에 없음 (서버에서 처리)"))
    func deleteTravel_byNonOwner_shouldThrowError() async {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 비즈니스 규칙 (기대 동작)                            │
        ├─────────────────────────────────────────────────────┤
        │ - 여행 삭제는 owner만 가능                           │
        │ - member는 삭제 불가, 탈퇴만 가능                    │
        ├─────────────────────────────────────────────────────┤
        │ 현재 상태                                           │
        │ - 권한 검증은 서버(API)에서 처리                     │
        │ - UseCase 레벨에서는 검증 없음                       │
        ├─────────────────────────────────────────────────────┤
        │ 참고                                                │
        │ - 이 TC는 통합 테스트에서 검증 필요                  │
        └─────────────────────────────────────────────────────┘
        */

        // 서버 권한 검증이므로 단위 테스트에서는 Skip
    }
}
