//
//  FetchTravelsUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/25.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("여행 목록 조회 UseCase 테스트", .tags(.useCase, .travel))
struct FetchTravelsUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-TRAVEL-010: 여행 목록 조회 성공")
    func fetchTravels_shouldReturnTravelList() async throws {
        // given
        let input = FetchTravelsInput(limit: 10, page: 1, status: .active)
        let useCase = FetchTravelsUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(!result.isEmpty)
        #expect(result.count <= 10) // limit 이하
    }

    @Test("TC-TRAVEL-011: 페이지네이션 - 첫 페이지")
    func fetchTravels_firstPage_shouldReturnItems() async throws {
        // given
        let input = FetchTravelsInput(limit: 5, page: 1, status: .active)
        let useCase = FetchTravelsUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.count <= 5)
    }

    @Test("TC-TRAVEL-012: 페이지네이션 - 두 번째 페이지")
    func fetchTravels_secondPage_shouldReturnDifferentItems() async throws {
        // given
        let useCase = FetchTravelsUseCase()
        let firstPageInput = FetchTravelsInput(limit: 5, page: 1, status: .active)
        let secondPageInput = FetchTravelsInput(limit: 5, page: 2, status: .active)

        // when
        let firstPage = try await useCase.execute(input: firstPageInput)
        let secondPage = try await useCase.execute(input: secondPageInput)

        // then
        if !firstPage.isEmpty && !secondPage.isEmpty {
            let firstIds = Set(firstPage.map { $0.id })
            let secondIds = Set(secondPage.map { $0.id })
            #expect(firstIds.isDisjoint(with: secondIds)) // 중복 없음
        }
    }

    @Test("TC-TRAVEL-013: 상태별 필터링 - active")
    func fetchTravels_withActiveStatus_shouldReturnActiveOnly() async throws {
        // given
        let input = FetchTravelsInput(limit: 10, page: 1, status: .active)
        let useCase = FetchTravelsUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        for travel in result {
            #expect(travel.status == .active)
        }
    }

    // MARK: - Edge Case Tests

    @Test("TC-TRAVEL-014: 빈 결과 - 존재하지 않는 페이지")
    func fetchTravels_withHighPageNumber_shouldReturnEmpty() async throws {
        // given
        let input = FetchTravelsInput(limit: 10, page: 9999, status: .active)
        let useCase = FetchTravelsUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.isEmpty)
    }

    @Test("TC-TRAVEL-015: 다양한 limit 값", arguments: [1, 5, 10, 20, 50])
    func fetchTravels_withVariousLimits_shouldRespectLimit(limit: Int) async throws {
        // given
        let input = FetchTravelsInput(limit: limit, page: 1, status: .active)
        let useCase = FetchTravelsUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        #expect(result.count <= limit)
    }

    @Test("TC-TRAVEL-016: archived 상태 여행 조회",
          .disabled("Known Issue: MockTravelRepository가 archived 상태 필터링을 지원하지 않음"))
    func fetchTravels_withArchivedStatus_shouldReturnArchivedOnly() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 데이터 이슈                                     │
        ├─────────────────────────────────────────────────────┤
        │ - MockTravelRepository가 status 필터링을 구현하지 않음 │
        │ - archived 요청해도 active 여행만 반환됨              │
        ├─────────────────────────────────────────────────────┤
        │ 수정 필요                                           │
        │ - MockTravelRepository에 status 필터링 추가         │
        │ - 또는 archived 상태의 mock 데이터 추가              │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let input = FetchTravelsInput(limit: 10, page: 1, status: .archived)
        let useCase = FetchTravelsUseCase()

        // when
        let result = try await useCase.execute(input: input)

        // then
        for travel in result {
            #expect(travel.status == .archived)
        }
    }
}
