//
//  UpdateTravelUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/25.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("여행 수정 UseCase 테스트", .tags(.useCase, .travel))
struct UpdateTravelUseCaseTests {

    // MARK: - Test Fixtures

    private func makeUpdateInput(
        title: String = "수정된 여행",
        startDate: Date = Date(),
        endDate: Date = Date().addingTimeInterval(86400 * 5)
    ) -> UpdateTravelInput {
        UpdateTravelInput(
            title: title,
            startDate: startDate,
            endDate: endDate,
            countryCode: "KR",
            koreanCountryName: "대한민국",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0,
            destinationCurrency: "KRW"
        )
    }

    // MARK: - Happy Path Tests

    @Test("TC-TRAVEL-017: 여행 제목 수정",
          .disabled("Known Issue: MockTravelRepository.update가 구현되지 않음"))
    func updateTravel_withNewTitle_shouldUpdateTitle() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 데이터 이슈                                     │
        ├─────────────────────────────────────────────────────┤
        │ - MockTravelRepository.update()가 항상 404 에러     │
        │ - Mock 데이터에 업데이트 로직이 없음                  │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-1"
        let input = makeUpdateInput(title: "변경된 제주도 여행")
        let useCase = UpdateTravelUseCase()

        // when
        let result = try await useCase.execute(id: travelId, input: input)

        // then
        #expect(result.title == "변경된 제주도 여행")
        #expect(result.id == travelId)
    }

    @Test("TC-TRAVEL-018: 여행 날짜 수정",
          .disabled("Known Issue: MockTravelRepository.update가 구현되지 않음"))
    func updateTravel_withNewDates_shouldUpdateDates() async throws {
        // given
        let travelId = "MOCK-1"
        let newStartDate = Date().addingTimeInterval(86400 * 7) // 1주일 후
        let newEndDate = Date().addingTimeInterval(86400 * 14) // 2주일 후
        let input = makeUpdateInput(startDate: newStartDate, endDate: newEndDate)
        let useCase = UpdateTravelUseCase()

        // when
        let result = try await useCase.execute(id: travelId, input: input)

        // then
        #expect(result.id == travelId)
        // 날짜 비교 (초 단위까지만)
        let calendar = Calendar.current
        #expect(calendar.isDate(result.startDate, equalTo: newStartDate, toGranularity: .second))
        #expect(calendar.isDate(result.endDate, equalTo: newEndDate, toGranularity: .second))
    }

    @Test("TC-TRAVEL-019: 여행 국가 정보 수정",
          .disabled("Known Issue: MockTravelRepository.update가 구현되지 않음"))
    func updateTravel_withNewCountry_shouldUpdateCountry() async throws {
        // given
        let travelId = "MOCK-1"
        let input = UpdateTravelInput(
            title: "일본 여행으로 변경",
            startDate: Date(),
            endDate: Date().addingTimeInterval(86400 * 5),
            countryCode: "JP",
            koreanCountryName: "일본",
            baseCurrency: "KRW",
            baseExchangeRate: 1.0,
            destinationCurrency: "JPY"
        )
        let useCase = UpdateTravelUseCase()

        // when
        let result = try await useCase.execute(id: travelId, input: input)

        // then
        #expect(result.countryCode == "JP")
        #expect(result.koreanCountryName == "일본")
        #expect(result.destinationCurrency == "JPY")
    }

    // MARK: - Error Case Tests

    @Test("TC-TRAVEL-020: 존재하지 않는 여행 수정 시도")
    func updateTravel_withInvalidId_shouldThrowError() async throws {
        // given
        let invalidId = "NON-EXISTENT-ID"
        let input = makeUpdateInput()
        let useCase = UpdateTravelUseCase()

        // when & then
        await #expect(throws: (any Error).self) {
            try await useCase.execute(id: invalidId, input: input)
        }
    }

    // MARK: - Edge Case Tests

    @Test("TC-TRAVEL-021: 동일한 값으로 수정 (변경 없음)",
          .disabled("Known Issue: MockTravelRepository.update가 구현되지 않음"))
    func updateTravel_withSameValues_shouldSucceed() async throws {
        // given
        let travelId = "MOCK-1"
        let input = makeUpdateInput(title: "여행 1") // Mock 데이터의 기본 제목
        let useCase = UpdateTravelUseCase()

        // when
        let result = try await useCase.execute(id: travelId, input: input)

        // then
        #expect(result.id == travelId)
    }

    // MARK: - Validation Tests (Known Issues)

    @Test("TC-TRAVEL-022: 빈 제목으로 수정 시도",
          .disabled("Known Issue: UpdateTravelInput에 제목 유효성 검증 없음"))
    func updateTravel_withEmptyTitle_shouldThrowError() async {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 비즈니스 규칙 (기대 동작)                            │
        ├─────────────────────────────────────────────────────┤
        │ - 수정 시에도 제목은 필수                            │
        │ - 빈 문자열로 수정 불가                              │
        ├─────────────────────────────────────────────────────┤
        │ 현재 상태                                           │
        │ - UpdateTravelInput에 유효성 검증 없음               │
        │ - 빈 제목으로도 수정됨                               │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-1"
        let input = makeUpdateInput(title: "")
        let useCase = UpdateTravelUseCase()

        // then: 기대 - TravelValidationError.emptyTitle throw
        // 현재는 빈 제목으로 수정됨
    }

    @Test("TC-TRAVEL-023: 수정 시 종료일이 시작일보다 이전인 경우",
          .disabled("Known Issue: 날짜 유효성 검증 없음"))
    func updateTravel_withInvalidDateRange_shouldThrowError() async {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 비즈니스 규칙 (기대 동작)                            │
        ├─────────────────────────────────────────────────────┤
        │ - 수정 시에도 종료일 >= 시작일 유지                  │
        ├─────────────────────────────────────────────────────┤
        │ 현재 상태                                           │
        │ - 날짜 순서 검증 없음                                │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-1"
        let startDate = Date()
        let endDate = startDate.addingTimeInterval(-86400) // 하루 전
        let input = makeUpdateInput(startDate: startDate, endDate: endDate)
        let useCase = UpdateTravelUseCase()

        // then: 기대 - TravelValidationError.invalidDateRange throw
    }
}
