//
//  DelegateOwnerUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/26.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("관리자 권한 위임 UseCase 테스트", .tags(.useCase, .member))
struct DelegateOwnerUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-MEMBER-020: 유효한 newOwnerId로 권한 위임 성공")
    func delegateOwner_withValidIds_shouldReturnUpdatedTravel() async throws {
        // given
        let travelId = "MOCK-1"
        let newOwnerId = "MOCKmember-1"
        let useCase = DelegateOwnerUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)

        // then
        #expect(result.id == travelId)
        #expect(result.ownerName == "친구1") // Mock에서 MOCKmember-{i}의 name은 "친구1"
    }

    @Test("TC-MEMBER-023: 권한 위임 후 반환된 Travel 정보 검증")
    func delegateOwner_shouldPreserveTravelInfo() async throws {
        // given
        let travelId = "MOCK-1"
        let newOwnerId = "MOCKmember-1"
        let useCase = DelegateOwnerUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)

        // then - 기본 정보가 유지되어야 함
        #expect(result.id == travelId)
        #expect(result.title == "여행 1")
        #expect(result.status == .active)
        #expect(result.inviteCode == "INV-0001")
    }

    // MARK: - Error Cases

    @Test("TC-MEMBER-021: 존재하지 않는 travelId로 위임 시 에러")
    func delegateOwner_withInvalidTravelId_shouldThrowError() async throws {
        // given
        let travelId = "INVALID-TRAVEL-ID"
        let newOwnerId = "any-member-id"
        let useCase = DelegateOwnerUseCase()

        // when & then
        await #expect(throws: Error.self) {
            _ = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)
        }
    }

    @Test("TC-MEMBER-024: 빈 문자열 travelId로 위임 시 에러")
    func delegateOwner_withEmptyTravelId_shouldThrowError() async throws {
        // given
        let travelId = ""
        let newOwnerId = "any-member-id"
        let useCase = DelegateOwnerUseCase()

        // when & then
        await #expect(throws: Error.self) {
            _ = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)
        }
    }

    // MARK: - Edge Cases

    @Test("TC-MEMBER-022: 존재하지 않는 newOwnerId로 위임 시 기존 ownerName 유지")
    func delegateOwner_withInvalidNewOwnerId_shouldKeepOriginalOwnerName() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 동작 설명                                       │
        ├─────────────────────────────────────────────────────┤
        │ - MockTravelMemberRepository는 newOwnerId를          │
        │   members에서 찾지 못하면 기존 ownerName을 유지함      │
        │ - 이는 실제 서버 동작과 다를 수 있음                    │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-2"
        let newOwnerId = "INVALID-MEMBER-ID"
        let useCase = DelegateOwnerUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)

        // then - 존재하지 않는 멤버이므로 기존 ownerName 유지
        #expect(result.ownerName == "김민희")
    }

    @Test("TC-MEMBER-025: 다양한 travelId로 권한 위임", arguments: ["MOCK-3", "MOCK-4", "MOCK-5"])
    func delegateOwner_withVariousTravelIds_shouldSucceed(travelId: String) async throws {
        // given
        let index = travelId.replacingOccurrences(of: "MOCK-", with: "")
        let newOwnerId = "MOCKmember-\(index)"
        let useCase = DelegateOwnerUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)

        // then
        #expect(result.id == travelId)
        #expect(result.ownerName == "친구1")
    }

    @Test("TC-MEMBER-026: 권한 위임 후 members 배열 유지 확인")
    func delegateOwner_shouldPreserveMembers() async throws {
        // given
        let travelId = "MOCK-6"
        let newOwnerId = "MOCKmember-6"
        let useCase = DelegateOwnerUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId, newOwnerId: newOwnerId)

        // then - members 배열이 유지되어야 함
        #expect(result.members.isEmpty == false)
    }
}
