//
//  DeleteTravelMemberUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/26.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("멤버 삭제 UseCase 테스트", .tags(.useCase, .member))
struct DeleteTravelMemberUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-MEMBER-010: 유효한 memberId로 멤버 삭제 성공")
    func deleteMember_withValidIds_shouldSucceed() async throws {
        // given
        let travelId = "MOCK-1"
        let memberId = "MOCKmember-1"
        let useCase = DeleteTravelMemberUseCase()

        // when & then - 에러가 발생하지 않으면 성공
        try await useCase.execute(travelId: travelId, memberId: memberId)
    }

    @Test("TC-MEMBER-012: 존재하지 않는 memberId로 삭제 시 성공")
    func deleteMember_withInvalidMemberId_shouldSucceed() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 동작 설명                                       │
        ├─────────────────────────────────────────────────────┤
        │ - MockTravelMemberRepository는 존재하지 않는          │
        │   memberId로 삭제해도 에러를 발생시키지 않음           │
        │ - filter를 사용하여 해당 멤버만 제외하므로             │
        │   없는 멤버를 삭제해도 정상 동작함                     │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-1"
        let memberId = "INVALID-MEMBER-ID"
        let useCase = DeleteTravelMemberUseCase()

        // when & then - 존재하지 않는 memberId도 에러 없이 처리됨
        try await useCase.execute(travelId: travelId, memberId: memberId)
    }

    // MARK: - Error Cases

    @Test("TC-MEMBER-011: 존재하지 않는 travelId로 삭제 시 에러")
    func deleteMember_withInvalidTravelId_shouldThrowError() async throws {
        // given
        let travelId = "INVALID-TRAVEL-ID"
        let memberId = "any-member-id"
        let useCase = DeleteTravelMemberUseCase()

        // when & then
        await #expect(throws: Error.self) {
            try await useCase.execute(travelId: travelId, memberId: memberId)
        }
    }

    @Test("TC-MEMBER-013: 빈 문자열 travelId로 삭제 시 에러")
    func deleteMember_withEmptyTravelId_shouldThrowError() async throws {
        // given
        let travelId = ""
        let memberId = "any-member-id"
        let useCase = DeleteTravelMemberUseCase()

        // when & then
        await #expect(throws: Error.self) {
            try await useCase.execute(travelId: travelId, memberId: memberId)
        }
    }

    // MARK: - Edge Cases

    @Test("TC-MEMBER-014: 다양한 travelId로 멤버 삭제", arguments: ["MOCK-2", "MOCK-3", "MOCK-4"])
    func deleteMember_withVariousTravelIds_shouldSucceed(travelId: String) async throws {
        // given
        let memberId = "MOCKmember-\(travelId.replacingOccurrences(of: "MOCK-", with: ""))"
        let useCase = DeleteTravelMemberUseCase()

        // when & then
        try await useCase.execute(travelId: travelId, memberId: memberId)
    }

    @Test("TC-MEMBER-015: 동일 멤버 연속 삭제 시도")
    func deleteMember_sameMemberTwice_shouldSucceedBothTimes() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ 동작 설명                                            │
        ├─────────────────────────────────────────────────────┤
        │ - 첫 번째 삭제: 멤버가 실제로 제거됨                   │
        │ - 두 번째 삭제: 이미 없는 멤버이므로 아무 동작 없음     │
        │ - 두 번 모두 에러 없이 완료됨                          │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-5"
        let memberId = "MOCKmember-5"
        let useCase = DeleteTravelMemberUseCase()

        // when & then - 두 번 삭제해도 에러 없음
        try await useCase.execute(travelId: travelId, memberId: memberId)
        try await useCase.execute(travelId: travelId, memberId: memberId)
    }
}
