//
//  FetchMemberUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/26.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("멤버 조회 UseCase 테스트", .tags(.useCase, .member))
struct FetchMemberUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-MEMBER-001: 유효한 travelId로 멤버 조회 성공")
    func fetchMember_withValidTravelId_shouldReturnMyTravelMember() async throws {
        // given
        let travelId = "MOCK-1"
        let useCase = FetchMemberUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId)

        // then
        #expect(result.myInfo.id.isEmpty == false)
        #expect(result.myInfo.name.isEmpty == false)
    }

    @Test("TC-MEMBER-003: myInfo가 owner 역할인지 확인")
    func fetchMember_shouldReturnOwnerAsMyInfo() async throws {
        // given
        let travelId = "MOCK-1"
        let useCase = FetchMemberUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId)

        // then
        #expect(result.myInfo.role == .owner)
    }

    @Test("TC-MEMBER-005: memberInfo 배열 유효성 확인")
    func fetchMember_shouldReturnValidMemberInfo() async throws {
        // given
        let travelId = "MOCK-1"
        let useCase = FetchMemberUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId)

        // then
        // memberInfo는 빈 배열일 수 있지만, 요소가 있다면 유효해야 함
        for member in result.memberInfo {
            #expect(member.id.isEmpty == false)
            #expect(member.name.isEmpty == false)
        }
    }

    // MARK: - Error Cases

    @Test("TC-MEMBER-002: 존재하지 않는 travelId로 조회 시 에러")
    func fetchMember_withInvalidTravelId_shouldThrowError() async throws {
        // given
        let travelId = "INVALID-TRAVEL-ID"
        let useCase = FetchMemberUseCase()

        // when & then
        await #expect(throws: Error.self) {
            _ = try await useCase.execute(travelId: travelId)
        }
    }

    @Test("TC-MEMBER-004: 빈 문자열 travelId로 조회 시 에러")
    func fetchMember_withEmptyTravelId_shouldThrowError() async throws {
        // given
        let travelId = ""
        let useCase = FetchMemberUseCase()

        // when & then
        await #expect(throws: Error.self) {
            _ = try await useCase.execute(travelId: travelId)
        }
    }

    // MARK: - Edge Cases

    @Test("TC-MEMBER-006: 다양한 travelId로 조회", arguments: ["MOCK-1", "MOCK-5", "MOCK-10", "MOCK-25"])
    func fetchMember_withVariousTravelIds_shouldSucceed(travelId: String) async throws {
        // given
        let useCase = FetchMemberUseCase()

        // when
        let result = try await useCase.execute(travelId: travelId)

        // then
        #expect(result.myInfo.id.isEmpty == false)
        #expect(result.myInfo.name.isEmpty == false)
    }
}
