//
//  JoinTravelUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/26.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("여행 참여 UseCase 테스트", .tags(.useCase, .member))
struct JoinTravelUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-MEMBER-030: 유효한 초대코드로 여행 참여 성공")
    func joinTravel_withValidInviteCode_shouldReturnTravel() async throws {
        // given
        let inviteCode = "INV-0001"
        let useCase = JoinTravelUseCase()

        // when
        let result = try await useCase.execute(inviteCode: inviteCode)

        // then
        #expect(result.id == "MOCK-1")
        #expect(result.inviteCode == inviteCode)
    }

    @Test("TC-MEMBER-032: 참여 후 멤버 수 증가 확인")
    func joinTravel_shouldIncreaseMemberCount() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 동작 설명                                       │
        ├─────────────────────────────────────────────────────┤
        │ - MockTravelMemberRepository는 joinTravel 호출 시    │
        │   새로운 멤버를 members 배열에 추가함                  │
        │ - 기존 멤버 1명 + 새 멤버 1명 = 최소 2명               │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let inviteCode = "INV-0002"
        let useCase = JoinTravelUseCase()

        // when
        let result = try await useCase.execute(inviteCode: inviteCode)

        // then - 멤버가 최소 1명 이상 존재해야 함
        #expect(result.members.isEmpty == false)
    }

    @Test("TC-MEMBER-035: 참여 후 반환된 Travel 정보 검증")
    func joinTravel_shouldReturnValidTravelInfo() async throws {
        // given
        let inviteCode = "INV-0003"
        let useCase = JoinTravelUseCase()

        // when
        let result = try await useCase.execute(inviteCode: inviteCode)

        // then
        #expect(result.id == "MOCK-3")
        #expect(result.title == "여행 3")
        #expect(result.status == .active)
        #expect(result.ownerName.isEmpty == false)
    }

    // MARK: - Error Cases

    @Test("TC-MEMBER-031: 잘못된 초대코드로 참여 시 에러")
    func joinTravel_withInvalidInviteCode_shouldThrowError() async throws {
        // given
        let inviteCode = "INVALID-CODE"
        let useCase = JoinTravelUseCase()

        // when & then
        await #expect(throws: Error.self) {
            _ = try await useCase.execute(inviteCode: inviteCode)
        }
    }

    @Test("TC-MEMBER-033: 빈 초대코드로 참여 시 에러")
    func joinTravel_withEmptyInviteCode_shouldThrowError() async throws {
        // given
        let inviteCode = ""
        let useCase = JoinTravelUseCase()

        // when & then
        await #expect(throws: Error.self) {
            _ = try await useCase.execute(inviteCode: inviteCode)
        }
    }

    // MARK: - Edge Cases

    @Test("TC-MEMBER-034: 다양한 형식의 초대코드 테스트", arguments: ["INV-0004", "INV-0005", "INV-0009"])
    func joinTravel_withVariousInviteCodes_shouldSucceed(inviteCode: String) async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 동작 설명                                       │
        ├─────────────────────────────────────────────────────┤
        │ - Mock의 초대코드 형식: "INV-000{i}" (i: 1~25)        │
        │ - 예: INV-0001, INV-0002, ..., INV-00025             │
        │ - 10 이상의 경우 INV-00010 형식이 아닌 INV-00010 형식 │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let useCase = JoinTravelUseCase()

        // when
        let result = try await useCase.execute(inviteCode: inviteCode)

        // then
        #expect(result.inviteCode == inviteCode)
        #expect(result.id.isEmpty == false)
    }

    @Test("TC-MEMBER-036: 동일 초대코드로 여러 번 참여")
    func joinTravel_sameCodeMultipleTimes_shouldAddMultipleMembers() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 동작 설명                                       │
        ├─────────────────────────────────────────────────────┤
        │ - 동일한 초대코드로 여러 번 참여하면                   │
        │   매번 새로운 멤버가 추가됨                           │
        │ - 실제 서버에서는 중복 참여 방지 로직이 있을 수 있음    │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let inviteCode = "INV-0006"
        let useCase = JoinTravelUseCase()

        // when - 두 번 참여
        let firstResult = try await useCase.execute(inviteCode: inviteCode)
        let secondResult = try await useCase.execute(inviteCode: inviteCode)

        // then - 멤버 수가 증가해야 함
        #expect(secondResult.members.count > firstResult.members.count)
    }

    @Test("TC-MEMBER-037: 새로 추가된 멤버의 역할 확인")
    func joinTravel_newMember_shouldHaveMemberRole() async throws {
        // given
        let inviteCode = "INV-0007"
        let useCase = JoinTravelUseCase()

        // when
        let result = try await useCase.execute(inviteCode: inviteCode)

        // then - 새로 추가된 멤버는 .member 역할이어야 함
        let newMembers = result.members.filter { $0.id.hasPrefix("MOCK_JOIN_") }
        for member in newMembers {
            #expect(member.role == .member)
        }
    }
}
