//
//  LeaveTravelUseCaseTests.swift
//  DomainTests
//
//  Created by 홍석현 on 1/29/26.
//  Generated by Test Automation System
//

import Testing
import Foundation
@testable import Domain

@Suite("여행 탈퇴 UseCase 테스트", .tags(.useCase, .member))
struct LeaveTravelUseCaseTests {

    // MARK: - Happy Path Tests

    @Test("TC-MEMBER-040: 유효한 travelId로 여행 탈퇴 성공")
    func leaveTravel_withValidTravelId_shouldSucceed() async throws {
        // given
        let travelId = "MOCK-1"
        let useCase = LeaveTravelUseCase()

        // when & then - 에러가 발생하지 않으면 성공
        try await useCase.execute(travelId: travelId)
    }

    @Test("TC-MEMBER-044: 다양한 travelId로 탈퇴", arguments: ["MOCK-8", "MOCK-9", "MOCK-10"])
    func leaveTravel_withVariousTravelIds_shouldSucceed(travelId: String) async throws {
        // given
        let useCase = LeaveTravelUseCase()

        // when & then
        try await useCase.execute(travelId: travelId)
    }

    // MARK: - Error Cases

    @Test("TC-MEMBER-041: 존재하지 않는 travelId로 탈퇴 시 에러")
    func leaveTravel_withInvalidTravelId_shouldThrowError() async throws {
        // given
        let travelId = "INVALID-TRAVEL-ID"
        let useCase = LeaveTravelUseCase()

        // when & then
        await #expect(throws: Error.self) {
            try await useCase.execute(travelId: travelId)
        }
    }

    @Test("TC-MEMBER-042: 빈 문자열 travelId로 탈퇴 시 에러")
    func leaveTravel_withEmptyTravelId_shouldThrowError() async throws {
        // given
        let travelId = ""
        let useCase = LeaveTravelUseCase()

        // when & then
        await #expect(throws: Error.self) {
            try await useCase.execute(travelId: travelId)
        }
    }

    // MARK: - Edge Cases

    @Test("TC-MEMBER-043: 여러 번 탈퇴 시도")
    func leaveTravel_multipleTimes_shouldSucceedBothTimes() async throws {
        /*
        ┌─────────────────────────────────────────────────────┐
        │ Mock 동작 설명                                       │
        ├─────────────────────────────────────────────────────┤
        │ - MockTravelMemberRepository는 leaveTravel 호출 시   │
        │   "MOCK_LEAVE" ID를 가진 멤버를 제거함                │
        │ - 이미 탈퇴한 상태에서 다시 탈퇴해도 에러 없음          │
        │ - 실제 서버에서는 이미 탈퇴한 사용자 처리가 다를 수 있음 │
        └─────────────────────────────────────────────────────┘
        */

        // given
        let travelId = "MOCK-11"
        let useCase = LeaveTravelUseCase()

        // when & then - 두 번 탈퇴해도 에러 없음
        try await useCase.execute(travelId: travelId)
        try await useCase.execute(travelId: travelId)
    }

    @Test("TC-MEMBER-045: 연속적인 여러 여행 탈퇴")
    func leaveTravel_multipleTrips_shouldSucceed() async throws {
        // given
        let travelIds = ["MOCK-12", "MOCK-13", "MOCK-14"]
        let useCase = LeaveTravelUseCase()

        // when & then
        for travelId in travelIds {
            try await useCase.execute(travelId: travelId)
        }
    }

    @Test("TC-MEMBER-046: 특수 문자가 포함된 travelId로 탈퇴 시 에러")
    func leaveTravel_withSpecialCharacters_shouldThrowError() async throws {
        // given
        let travelId = "MOCK@#$%"
        let useCase = LeaveTravelUseCase()

        // when & then - Mock에서 찾을 수 없으므로 에러 발생
        await #expect(throws: Error.self) {
            try await useCase.execute(travelId: travelId)
        }
    }
}
